[phases.setup]
cmds = [
    "python --version",
    "pip install --upgrade pip setuptools wheel"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python main.py"
