[phases.setup]
cmds = [
    "apt-get update && apt-get install -y python3-pip",
    "pip3 install --upgrade pip setuptools wheel"
]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "python main.py"
